site_name: Retrobatch JavaScript API

pages:
    - Introduction: index.md
    - Plug-In Basics: pluginanatomy.md
    - Asset API: assetapi.md
    - Image Accumulator API: accumulatorapi.md
    - Document API: documentapi.md
    - Debugging: debugging.md
    - JavaScript Node: javascriptnode.md
    
theme:
    name: readthedocs
    custom_dir: rbtheme/